# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Ignacio Rios
first_name: Ignacio
middle_name:
last_name: Rios
email: ignacio.rios@utdallas.edu
description: >
  Academic website of Ignacio Rios, Assistant Professor at UT Dallas Naveen Jindal School of Management.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: operations-research, matching-markets, school-choice, college-admissions, behavioral-operations

lang: en
icon: ⚙️

url: https://iriosu.github.io
baseurl:
last_updated: false

# -----------------------------------------------------------------------------
# Theme settings
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: true
serve_schema_org: true
og_image: /assets/img/prof_pic.jpg

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: iriosu
linkedin_username: ignacio-rios-25b07228
scholar_userid: pgmk7egAAAAJ
orcid_id:
research_gate_profile: Ignacio_Rios2

# Contact (Displayed on contact page)
contact_note: >
  Feel free to reach out via email!

# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------

google_analytics: UA-147147142-1
google_site_verification:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# defaults for collections
defaults:
  - scope:
      path: ""
    values:
      nav: true
  - scope:
      path: "assets"
      type: pages
    values:
      nav: false

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & Coverage
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-target-blank
  - jekyll-toc
  - jemoji

# Sitemap settings
sitemap:
  exclude:
    - /assets/
    - /feed.xml
    - /sitemap.xml

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Rios]
  first_name: [Ignacio, I.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  
  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# -----------------------------------------------------------------------------
# Jekyll Archives (for blog posts)
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# Sass/SCSS
sass:
  style: compressed

# -----------------------------------------------------------------------------
# Extras
# -----------------------------------------------------------------------------

enable_google_analytics: true
enable_cronitor_analytics: false

enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true

enable_medium_zoom: true
enable_progressbar: true
enable_tooltips: true
show_social_icons: true

# Filter out certain bibtex entry keywords used internally 
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview, altmetric]

# Maximum number of authors to display differently
max_author_limit: 3
more_authors_animation_delay: 10

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true
